// <auto-generated />
using Demo2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demo2.Migrations
{
    [DbContext(typeof(FootballDbContext))]
    partial class FootballDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Demo2.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Appearances")
                        .HasColumnType("int");

                    b.Property<int>("Goals")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("ShirtNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Appearances = 268,
                            Goals = 54,
                            Name = "Juan Mata",
                            Position = 3,
                            ShirtNo = 8
                        },
                        new
                        {
                            Id = 2,
                            Appearances = 130,
                            Goals = 28,
                            Name = "Paul Pogba",
                            Position = 2,
                            ShirtNo = 6
                        },
                        new
                        {
                            Id = 3,
                            Appearances = 335,
                            Goals = 0,
                            Name = "David de Gea",
                            Position = 0,
                            ShirtNo = 1
                        },
                        new
                        {
                            Id = 4,
                            Appearances = 200,
                            Goals = 2,
                            Name = "Phil Jones",
                            Position = 1,
                            ShirtNo = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
